### ISSUE TITLE
Set and adjust difficulty ratings before launch

### ISSUE THREAD

**Issue by vaeng** [exercism/sqlite#22]

**Comment by vaeng** [comment]
With exercise number 20 just added, we can prepare for launch. Please add your votes for exercise difficulties, so we can adjust the difficulties and sort the config.json file accordingly.

| Exercise | Current difficulty | Votes for Easy | Votes for  Medium | Votes for  Hard |
| -------- | ------- | ---- | ------ | --------- |
| Hello World | 1 | | | |
| Raindrops | 1 | | | |
| Leap | 1 | | | |
| Bob | 5 | | | |
| Gigasecond | 1 | | | |
| Isogram | 1 | | | |
| Collatz Conjecture | 5 | | | |
| Allergies | 3 | | | |
| Meetup | 5 | | | |
| Two-Fer | 2 | | | |
| Yacht | 1 | | | |
| Nucleotide Count | 1 | | | |
| Resistor Color | 1 | | | |
| High Scores | 3 | | | |
| Darts | 2 | | | |
| Grains | 1 | | | |
| Luhn | 4 | | | |
| Eliud's Eggs | 3 | | | |
| Armstrong Numbers | 3 | | | |
| Difference of Squares | 1 | | | |

Please edit this post, so I can see it all in one place to update the config. @BNAndras, @glennj , @IsaacG

**Comment by IsaacG** [comment]
```
» wc --total=never -l */.meta/example.sql | sort -n
    1 hello-world/.meta/example.sql
    2 gigasecond/.meta/example.sql
    2 leap/.meta/example.sql
    5 raindrops/.meta/example.sql
    6 grains/.meta/example.sql
    7 two-fer/.meta/example.sql
   11 difference-of-squares/.meta/example.sql
   14 eliuds-eggs/.meta/example.sql
   15 darts/.meta/example.sql
   21 collatz-conjecture/.meta/example.sql
   22 meetup/.meta/example.sql
   27 bob/.meta/example.sql
   27 resistor-color/.meta/example.sql
   28 resistor-color-duo/.meta/example.sql
   29 allergies/.meta/example.sql
   30 armstrong-numbers/.meta/example.sql
   31 nucleotide-count/.meta/example.sql
   38 isogram/.meta/example.sql
   42 luhn/.meta/example.sql
   54 yacht/.meta/example.sql
   69 high-scores/.meta/example.sql
```

If there exercises were one task each, I'd say line count is a good measure ;) But the multi-tasks throws that off.

**Comment by IsaacG** [comment]
I added my votes to the table.

**Comment by BNAndras** [comment]
My votes are added as well.

**Comment by vaeng** [comment]
Glenn said we should continue without him for a moment.
I took our votes and made a PR: #56
