### ISSUE TITLE
Min version to target

### ISSUE THREAD

**Issue by vaeng** [exercism/sqlite#32]
I think we should agree on the mininum version of sqlite we want to target with this track.

I would love to [work with json objects](https://sqlite.org/json1.html), as it makes things a lot more interesting, but it is not completely supported by all version.

There are some compatibility issues, like the use of `iff` or `format`, that users migth face, if we "go too low".

What are your thougths? My Ubuntu 22.04 comes with 3.37.2, and that is the current limit for my example solutions, but I don't mind going newer so students can use a syntax that is closer to postgres etc.
Curiously, my version is compiledwith json support, but that is only opt-out in 3.38 and we cannot be "sure" if students have it with older versions.

"Milestones" as I see them:
- 3.38 out-of-the box json support, `->` and `->>`  json operators and `format` for better compatibility
- 3.39 `RIGHT` and `FULL OUTER JOIN` support
- 3.42 json5 extension support
- 3.44 additional functionality and compatibility with other SQL languages for date, time and aggregate functions

More info in change history: https://www.sqlite.org/changes.html

**Comment by IsaacG** [comment]
I'm fine following the Ubuntu release. It's a pretty common "base".

**Comment by BNAndras** [comment]
[Fedora 39 is at  3.45](https://koji.fedoraproject.org/koji/packageinfo?packageID=485).

--

[Debian Stable is at 3.40](https://packages.debian.org/bookworm/sqlite3).

--

[Ubuntu LTS is at 3.37](https://packages.ubuntu.com/jammy/sqlite3).
[Ubuntu non-LTS is at 3.42](https://packages.ubuntu.com/mantic/sqlite3)


If we're okay with the Ubuntu LTS folks needing to source a newer version, 3.39 and 3.44 both sound useful. If we do want 3.42, the Debian folks will need to source a newer version, but they'll need to do that sooner or later anyways if we keep incrementing the version.

For now, we can stay with 3.37 and then switch to 3.38 or 3.44 when they're available on Ubuntu. That'll simplify install directions for the most people.

**Comment by vaeng** [comment]
So all three main distros have versions with json support. I'm okay with ubuntu's 3.37 package and might write some exercises with json data, as that is more interesting than picking strings apart the manual way.

**Comment by IsaacG** [comment]
[REST API](https://github.com/exercism/problem-specifications/blob/main/exercises/rest-api/canonical-data.json) is sometimes done with JSON.

**Comment by vaeng** [comment]
As we decided on a lower limit, we can close this issue.
